# Generated by Django 5.1.7 on 2025-03-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='required_courses',
            field=models.ManyToManyField(blank=True, related_name='required_by_departments', to='courses.course'),
        ),
    ]
